### ISSUE TITLE
Issue - zoom state not updated when persp is renamed

### ISSUE THREAD

**Issue by samrjack** [emacsorphanage/zoom-window#22]
# Issue
When using persp, it is possible to rename a perspective using `persp-rename`. `zoom-window` tracks perspectives' states using their name so when that name gets changed, the entire state can be messed up; especially if you are zoomed in when that renaming occurs.

# Solution
The easiest way to solve this is to add a hook function to the `persp-renamed-functions` hook which will notify you when a name change has taken place. That can then go an update the `zoom-window-persp-alist` variable to reflect the new name.

**Comment by samrjack** [comment]
I'm going to try to make a PR for this, just wanted wanted to raise an issue for reference.

**Comment by samrjack** [comment]
Fix has been merged so this ticket can be closed.

**Comment by jcs090218** [comment]
Ah, thanks! I forgot to close it. 😓
