### ISSUE TITLE
Enable GitHub Actions

### ISSUE THREAD

**Issue by jcs090218** [emacsorphanage/zoom-window#24]
The same request like https://github.com/emacsorphanage/quickrun/issues/141/.

Can you enable GitHub Actions for all repos I am maintaining?

* https://github.com/emacsorphanage/zoom-window (this)
* https://github.com/emacsorphanage/undohist
* https://github.com/emacsorphanage/yascroll
* https://github.com/emacsorphanage/sound-wav
* https://github.com/emacsorphanage/manage-minor-mode
* https://github.com/emacsorphanage/popwin
* https://github.com/emacsorphanage/helm-themes
* https://github.com/emacsorphanage/helm-gtags
* https://github.com/emacsorphanage/helm-ag
* https://github.com/emacsorphanage/haxe-mode
* https://github.com/emacsorphanage/applescript-mode
* https://github.com/emacsorphanage/git-gutter
* https://github.com/emacsorphanage/fontawesome

cc @tarsius Thank you!

**Comment by tarsius** [comment]
I've just enabled the same actions as for https://github.com/emacsorphanage/quickrun/issues/141 for all of these.

**Comment by tarsius** [comment]
Happy testing! :grinning:
